In [1]:
import json
import os
import numpy as np
import tensorflow as tf
from pathlib2 import Path
import preprocess
from data_loader import create_dataset, create_inputs

2021-12-08 15:41:06.580545: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-12-08 15:41:06.580581: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
def prepare_data(data_dir, language):
    if language == "Chinese":
        train_path = data_dir / "train_cn.json"
        test_path = data_dir / "test_cn.json"
        dev_path = data_dir / "dev_cn.json"

    elif language == "English":
        train_path = data_dir / "train_en.json"
        test_path = data_dir / "test_en.json"
        dev_path = data_dir / "dev_en.json"

    else:
        raise ValueError("Language must be English or Chinese")

    if not os.path.isfile(test_path):
        test_path = None

    return train_path, dev_path, test_path

data_dir = "./dataset"
language = "Chinese"
train_path, dev_path, test_path = prepare_data(data_dir=Path(data_dir), language=language)
train_path, dev_path, test_path

(PosixPath('dataset/train_cn.json'), PosixPath('dataset/dev_cn.json'), None)

In [3]:
dataset = create_dataset(str(train_path), "BERT", 256, "train", "Chinese", "nugget")

2021-12-08 15:41:07.668935: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-12-08 15:41:07.668973: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-12-08 15:41:07.668987: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (DESKTOP-EFG9I9T): /proc/driver/nvidia/version does not exist
2021-12-08 15:41:07.669186: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
a = list(dataset.take(1))
a

[{'input_ids': <tf.Tensor: shape=(16, 256), dtype=int32, numpy=
  array([[ 101, 6380, 7607, ...,    0,    0,    0],
         [ 101,  137,  704, ...,    0,    0,    0],
         [ 101,  137,  704, ...,    0,    0,    0],
         ...,
         [ 101,  137,  704, ...,    0,    0,    0],
         [ 101,  137, 3180, ...,    0,    0,    0],
         [ 101, 7237, 2094, ...,    0,    0,    0]], dtype=int32)>,
  'input_mask': <tf.Tensor: shape=(16, 256), dtype=int32, numpy=
  array([[1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0],
         ...,
         [1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>,
  'input_type_ids': <tf.Tensor: shape=(16, 256), dtype=int32, numpy=
  array([[0, 0, 0, ..., 1, 1, 1],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=i

In [9]:
tf.math.count_nonzero(a[0]["sentence_masks"][0], axis=-1).numpy()

5

In [ ]:
dataset = create_dataset(data, "nugget")
a = list(dataset.take(1))

In [ ]:
a

In [ ]:
import tensorflow as tf
def gen(n):
    for i in range(n):
        yield i, 2*i + 1

from functools import partial

def get_dataset():
    dataset = tf.data.Dataset.from_generator(partial(gen, 10),
                                            output_types=(tf.int32, tf.int32))
    dataset = dataset.batch(3).repeat()
    return dataset


In [ ]:
dataset = get_dataset()
a = list(dataset.take(100))
a

In [ ]:
b = list(dataset2.take(1))
b

In [ ]:
dataset2.prefetch(2)

In [ ]:
for element in dataset2.as_numpy_iterator():
    print(element)

In [ ]:
for element in dataset2.as_numpy_iterator():
    print(element)

In [ ]:
b = list(dataset.take(50))

In [ ]:
b

In [ ]:
c = list(dataset.take(100))

In [ ]:
c